[project]
name = "spiral-dft-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cocotb>=2.0.0",
    "cocotb-test>=0.2.6",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
]
